appName: "Go Desk"

# 当前监听的端口
port: 6997

# ws 连接地址
wsUrl: "106.12.33.188:6996"

# STUN 服务器地址
stunUrl: "stun:106.12.33.188:3478"

# api地址
apiUrl: "http://106.12.33.188:6996"

# 网页文件保存目录
siteFileDir: "www"
